adobe/jsonschema2md

templates/md/definitions.ejs
templates/md/properties.ejs

Fixing #37 issue, and property links in Definitions by removing colons in links

bug #37 fix

---

examples/docs/complex.schema.md
examples/docs/deepextending.schema.md
examples/docs/extending.schema.md
lib/header.js
lib/markdownWriter.js
package.json
spec/examples/complex.schema.md
spec/examples/deepextending.schema.md
spec/examples/extending.schema.md
spec/lib/header.spec.js
spec/lib/integrationTest.spec.js
templates/md/header.ejs

This should make it a bit easier to implement #44 #35 and #36

Refactor Header Generation

---

examples/docs/deepextending.schema.md
examples/docs/definitions.schema.md
examples/docs/extending.schema.md
examples/docs/simpletypes.schema.md
examples/generated-schemas/definitions.schema.json
examples/schemas/definitions.description.md
spec/examples/deepextending.schema.md
spec/examples/definitions.schema.md
spec/examples/extending.schema.md
spec/examples/simpletypes.schema.md
templates/md/array-type.ejs
templates/md/header.ejs
templates/md/nested-property.ejs
templates/md/pattern-property.ejs
templates/md/property.ejs

Don't double-escape some markdown that's also HTML

---

cli.js
spec/lib/integrationTest.spec.js

Add CLI option to allow alternate extensions for schema's, with a test for the newly added -e flag.

Allow alternative extensions #43

---

README.md
package.json

Changes for 1.0.5 release

---

examples/docs/arrays.schema.md
examples/docs/complex.schema.md
spec/examples/arrays.schema.md
spec/examples/complex.schema.md
templates/md/nested-properties.ejs
templates/md/nested-property.ejs
templates/md/pattern-property.ejs
templates/md/properties.ejs
templates/md/property.ejs

added support for default

---

Contributing.md

📝tweaking CLA portion of contribution guidelines.

---

lib/readmeWriter.js
templates/md/readme.ejs

fixed broken readme links

---

README.md
package.json

Changes for 1.0.6 release

---

README.md
cli.js
package.json
spec/lib/integrationTest.spec.js

Draft 07 support

---

cli.js

This is a fix for the logger mis-configuration mentioned in #83

updated winston logger configuration

---

.circleci/config.yml
.releaserc.js
Contributing.md
package.json

Semantic release

---

package.json

Greenkeeper/GitHub slugger 1.2.1

---

spec/examples/abstract.schema.md
spec/examples/arrays.schema.md
spec/examples/complex.schema.md
spec/examples/constants.schema.md
spec/examples/custom.schema.md
spec/examples/deepextending.schema.md
spec/examples/definitions.schema.md
spec/examples/enums.schema.md
spec/examples/example.schema.md
spec/examples/examples.schema.md
spec/examples/extending.schema.md
spec/examples/extensible.schema.md
spec/examples/identifiable.schema.md
spec/examples/join.schema.md
spec/examples/nestedobj.schema.md
spec/examples/simple.schema.md
spec/examples/simpletypes.schema.md
spec/examples/stabilizing.schema.md
spec/examples/subdir/subdir.schema.md
spec/examples/typearrays.schema.md
templates/md/header.ejs
templates/md/nested-property.ejs
templates/md/property.ejs

Proposed changes to fix issue #117.

Issue #117: Add blank lines for proper HTML rendering with kramdown

---

package-lock.json
package.json

Greenkeeper/cz conventional changelog 3.0.2

---

package-lock.json
package.json

Greenkeeper/eslint 6.1.0

---

examples/docs/complex.schema.md
examples/generated-schemas/complex.schema.json
examples/schemas/complex.schema.json
lib/schema.js
spec/examples/complex.schema.md

Fix resolving $ref recursively

---

lib/traverseSchema.js

fix(cli): fix `traverse` function when called from CLI

---

lib/formattingTools.js
test/formatting.test.js

chore(tests): increase coverage

---

lib/markdownBuilder.js
test/fixtures/format/format.schema.json
test/markdownBuilder.test.js

Robust format

---

lib/locales/en_US.json
lib/markdownBuilder.js
package-lock.json
package.json
test/fixtures/type/button.schema.json
test/fixtures/type/type.schema.json
test/markdownBuilder.test.js
test/readmeBuilder.test.js

Hi @AndyOGo this is a test for #201 using the example you've provided. Unfortunately, the test is succeeding, which means I can't fully reproduce.
You can add to the test by adding more schemas (with `.schema.json` ending) into the `test/fixtures/type` folder. When you find a file that makes the tests fail, please let me know.

Type error tests and fixes

---

package-lock.json
package.json

- json-logic-js' fix/type-key-exception branch was merged into master, the branch does not exist anymore, preventing `npm i` from working - https://github.com/axa-ch/cyclic-schemas-test/pull/2
- Removed unused dependency (unist-builder)
- Moved mocha to devDeps

build(package.json): fix & clean up dependencies

---

README.md
lib/index.js
lib/markdownBuilder.js
package-lock.json
package.json
test/fixtures/format/format.schema.json
test/markdownBuilder.test.js

Enables formatting examples as YAML

Examples yaml

---

lib/markdownBuilder.js
package-lock.json
package.json
test/fixtures/enums/arrayenums.schema.json
test/markdownBuilder.test.js

Enum arrays

---

.eslintrc.js
cli.js
lib/formatInfo.js
lib/index.js
lib/keywords.js
lib/markdownBuilder.js
lib/readmeBuilder.js
lib/schemaProxy.js
lib/writeMarkdown.js
lib/writeSchema.js
package-lock.json
package.json
test/markdownBuilder.test.js
test/readmeBuilder.test.js
test/testUtils.js
test/testintegration.test.js
test/traverseSchema.test.js
test/zSchemaCoverage.test.js

Fix compatibility issues with remark

Remark update

---

lib/index.js

fix(index): remove reference to single input file

---

README.md
package.json

fix(package): bump minimum node version to 14

---

README.md
package.json

BREAKING CHANGE: required node 18

build: require node 18
