- examples/docs/deepextending.schema.md
- examples/docs/definitions.schema.md
- examples/docs/extending.schema.md
- examples/docs/identifiable.schema.md
- lib/markdownWriter.js
- package.json
- spec/examples/deepextending.schema.md
- spec/examples/definitions.schema.md
- spec/examples/extending.schema.md
- spec/examples/identifiable.schema.md
- spec/lib/integrationTest.spec.js
- templates/md/definitions.ejs
- templates/md/nested-property.ejs
- templates/md/object-type.ejs
- templates/md/properties.ejs
- templates/md/property.ejs
This will create correct links as github creates them, so as to navigate among schemas and properties. Used github-slugger module to generate slugs as github would generate for headings in markdown.
> Fixes #30, using a slugger to create links

- examples/docs/complex.schema.md
- examples/docs/enums.schema.md
- examples/generated-schemas/enums.schema.json
- examples/schemas/enums.schema.json
- lib/markdownWriter.js
- spec/examples/complex.schema.md
- spec/examples/enums.schema.md
- templates/md/object-type.ejs
Thanks for this nice doc generator.
This fixes #69 `enum`'s within nested properties don't get displayed.
> provide simpletype to ejs templates for reuse at nested props

- README.md
The module is published on npm under `@adobe` and as such needs to be references as `@adobe/jsonschema2md` for `npm install` or `yarn` to actually find the module on npm.
> Updated npm install instructions.

- examples/docs/subdir/subdir.schema.md
- lib/header.js
- spec/lib/header.spec.js
This resolves #64.
It always uses the "filename" as the link, and removes any subdirectories in the link.
The text of the link remains the same, to give context to which schema it actually is.
A unit test has been added with a sample of a subdir schema. (as per @trieloff 's excellent suggestion on the previous PR)
> resolve #64. subdir link to schema

- examples/docs/complex.schema.md
- examples/generated-schemas/complex.schema.json
- examples/schemas/complex.schema.json
- lib/schema.js
- spec/examples/complex.schema.md
> fix: Fix `$ref` within nested objects not generating correct markdown

- cli.js
- lib/markdownWriter.js
- lib/readmeWriter.js
- spec/lib/header.spec.js
fix #157 
Add path for loading the translation file.
Moved the init for i18n form markdownWriter and readmeWriter to cli.js
> fix:I18n fix

- lib/formattingTools.js
- lib/markdownBuilder.js
- lib/traverseSchema.js
- test/cyclicSchemaIntegration.test.js
- test/fixtures/cyclic/one.schema.json
- test/fixtures/cyclic/three.schema.json
- test/fixtures/cyclic/two.schema.json
- test/traverseSchema.test.js
I thought I'd already merged this one. It is the fix for #185
> Fix for cyclic schemas

- lib/schemaProxy.js
- test/fixtures/title/meta.schema.json
- test/markdownBuilder.test.js
> Robust slugger

- lib/index.js
When passing `-x -` on the command line, a schema is still created in the process' cwd.
This is because the `-x` value of `-` is coerced to an empty string.
Later on, it is tested against '-' instead of empty string.
Fixes https://github.com/adobe/jsonschema2md/issues/203
> fix(index.js): -x flag is not working properly for the suppression case

- package.json
this is in order to avoid running into https://github.com/skolmer/es2015-i18n-tag/issues/71
fixes #207
> fix(deps): pin es2015-i18n-tag version

- lib/index.js
Generating markdown on Windows uses the OS path seperator, backslash, not a valid URL path seperator
fix #211
> fix: dont use backslash for URLs on windows

- lib/index.js
fix #209
Currently setting `-h false` in the CLI will not work because the `header` value is set to the string `false`. In Javascript, a the string `false` is truthy, so the header will always be added.
I checked the yargs documentation and found that you can indicated that an argument should be treated as truth with [`.boolean()`](https://yargs.js.org/docs/#api-booleankey).
Made the changes and the feature seems to be working correctly since then.
> #209 fix(lib/index.js): made -h/--header a boolean arg

- lib/markdownBuilder.js
#226 Relocate definitons
Move the definition section to the bottom of output file.
> fix: moved definitions to bottom of output file

- lib/markdownBuilder.js
#228
fix: Definition object, definitions based on the property list structure
> fix: Definition object, definitions based on the property list structure

- lib/markdownBuilder.js
This reverts commit 2fb9fc5846b64df7cd54f39e3ef10f2da5cef75e.
See #240 
@alainlecluse this reverts #229, which broke some tests. Not sure why CI didn't mark the build as failing, but this should not have happened.
> Revert "fix: definition object defintions based on proplist structure"

- lib/markdownBuilder.js
- test/fixtures/nullable/array.schema.json
- test/markdownBuilder.test.js
> fix(markdown): correcly show type of nullable types in header

- lib/index.js
- lib/markdownBuilder.js
- test/fixtures/skipproperties/complete.schema.json
- test/markdownBuilder.test.js
- test/testUtils.js
#243 
With this change, users can choose which markdown blocks or items to skip.
The default behavior stays the same.
Currently I set up the flag for: 
* `arrayfact`,
* `typefact`, 
* `nullablefact`, 
* `definedinfact`,
* `typesection`,
* `proptable`
The existing code is changed by adding a new flag, `s` or `skip`. 
The markdown builder checks for this flag's properties before creating elements.
> #243 Create option to skip properties in markdown

- lib/markdownBuilder.js
This PR fixes #255 
Modified the file markdownBuilder.js.
In the function makepropheader, the anchor link is now transformed by github-slugger.
> Fixes #255: Property table anchor link, generated with github-slugger

- lib/markdownBuilder.js
If we don't provide a title for an object, the title of the Properties list will become "undefined
Properties". By using simpletitle we avoid this and be consistent with other titles.
> fix(lib/markdownBuilder.js): use simpletitle for makeproperties

- lib/traverseSchema.js
- test/traverseSchema.test.js
`properties`, `required` and `examples` should be skipped only when they are part of the 'object' or
'array' schema type. These should not be omitted when then are part of 'properties' object, for
instance.
Now, `isSkippableKeyword` checks also the parent's type of property - it should skip the property only if it's `object` or `array` type - otherwise there is no reason to skip it at all. This change has been originally introduces within [this change](https://github.com/adobe/jsonschema2md/commit/fc50969426fd2ed0b55752f6c58d9246a22e309c) however it got "refactored" in the next commit so it wasn't effectively considered.
I consider it more as a bug, especially it has been reported as a one in #282. 
BREAKING CHANGE: If schema contained 'properties', 'required' or 'examples' as a part of …
> fix(lib/traverseschema.js) #282 - valid 'properties' property is not rendered

- lib/schemaProxy.js
Fixes `UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded` on inputs.
Solution proposed by @bmaranville in
https://github.com/adobe/jsonschema2md/issues/252#issuecomment-806067867. Updated to work with
7.1.1.
Fixes https://github.com/adobe/jsonschema2md/issues/252
> #252 Fix error on inputs with circular references

- lib/markdownBuilder.js
- test/fixtures/enums/enum-meta-enum.schema.json
- test(markdown-builder): add test for enums
- fix(markdown-builder): guard against `enum` being not an array
fixes #458
> Prevent enum crash

- examples/docs/typearrays-properties-string-or-number-null.md
- examples/docs/typearrays-properties-string-or-number.md
- examples/docs/typearrays.md
- lib/locales/de.json
- lib/locales/en_US.json
- lib/locales/nl_NL.json
- lib/markdownBuilder.js
- test/markdownBuilder.test.js
Does not relate to an open issue (the `CONTRIBUTING.md` file says that I should use a `[trivial]` tag in my commit message, but it seems the last time anybody in this repo has done this was in 2018 in https://github.com/adobe/jsonschema2md/commit/55aa06991b5dc19042b4e5f0cada48343ec62540, so I'm not sure if this is still valid)
This issue was caught by https://www.npmjs.com/package/cspell, which was present in the the repo I was trying to add `jsonschema2md` too.
I've just done a simple find-and-replace everything in the repo, since running `npm run examples` seems to create a lot of changes that are unrelated to this change.
Should I modify my commit title to `fix(markdown-builder): fix typo in 'any of the following' text`? Or `fix(i18n): fix typo in 'any of the following' text`.
> fix: fix typo in 'any of the following' text

- lib/markdownBuilder.js
- test/fixtures/boolean-defaults/boolean-defaults.schema.json
- test/markdownBuilder.test.js
The `markdownBuilder` didn't render property defaults for `boolean` properties when the default was `false` due to a truthy check instead of `!== undefined`.
Added a regression test & fixed the issue.
I have signed the Adobe CLA; you can find it associated with this GitHub username.
> fix(markdownBuilder): boolean defaults didn't render when the default was false
